# Generated by Django 4.2.16 on 2024-11-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
